import { IsString, IsOptional, IsIn } from "class-validator";

export class SocialAuthDto {
  @IsString()
  @IsIn(["apple", "google"])
  provider!: "apple" | "google";

  /** The identity token (JWT) from Apple or Google ID token */
  @IsString()
  idToken!: string;

  /** Full name — Apple only sends this on first sign-in */
  @IsOptional()
  @IsString()
  fullName?: string;

  /**
   * Nonce generated by the client and embedded in the Apple/Google request.
   * When supplied it is checked against the identity token's `nonce` claim to
   * prevent replay. Enforcement is controlled server-side by
   * `SOCIAL_AUTH_REQUIRE_NONCE` / `SOCIAL_AUTH_NONCE_REQUIRED_AFTER`: it is only
   * accepted as absent during an explicit, time-bounded legacy-client window,
   * after which a request without a verifiable nonce is rejected. The transport
   * field stays optional so the server (not `class-validator`) owns that policy.
   */
  @IsOptional()
  @IsString()
  nonce?: string;
}
