import { IsString, IsOptional, IsIn } from "class-validator";

export class SocialAuthDto {
  @IsString()
  @IsIn(["apple", "google"])
  provider!: "apple" | "google";

  /** The identity token (JWT) from Apple or Google ID token */
  @IsString()
  idToken!: string;

  /** Full name — Apple only sends this on first sign-in */
  @IsOptional()
  @IsString()
  fullName?: string;

  /**
   * Optional nonce generated by the client and embedded in the Apple/Google
   * request. When supplied it is checked against the identity token's `nonce`
   * claim to prevent replay. The current mobile client does not send one, so it
   * remains optional; provide it end-to-end to enable replay protection.
   */
  @IsOptional()
  @IsString()
  nonce?: string;
}
