export type AdminPermissionDefinition = {
  key: string;
  module: string;
  description: string;
};

export const ADMIN_PERMISSION_DEFINITIONS: AdminPermissionDefinition[] = [
  { key: "dashboard.read", module: "dashboard", description: "View the admin dashboard" },
  { key: "audit.read", module: "audit", description: "View audit logs" },
  { key: "search.read", module: "search", description: "Use global admin search" },
  { key: "users.read", module: "users", description: "View users" },
  { key: "users.write", module: "users", description: "Update user profile data" },
  { key: "users.suspend", module: "users", description: "Suspend or reactivate users" },
  { key: "repits.read", module: "repits", description: "View repits" },
  { key: "repits.moderate", module: "repits", description: "Moderate repits" },
  { key: "repits.delete", module: "repits", description: "Delete repits" },
  { key: "templates.read", module: "templates", description: "View templates" },
  { key: "templates.write", module: "templates", description: "Create and edit templates" },
  { key: "templates.publish", module: "templates", description: "Publish template versions" },
  { key: "templates.rollback", module: "templates", description: "Rollback template versions" },
  { key: "templates.archive", module: "templates", description: "Archive templates" },
  { key: "spotlight.read", module: "spotlight", description: "View spotlight campaigns" },
  { key: "spotlight.write", module: "spotlight", description: "Create and edit spotlight campaigns" },
  { key: "spotlight.publish", module: "spotlight", description: "Publish spotlight campaigns" },
  { key: "spotlight.archive", module: "spotlight", description: "Archive spotlight campaigns" },
  { key: "spotlight.schedule", module: "spotlight", description: "Schedule spotlight campaigns" },
  { key: "support.read", module: "support", description: "View support tickets" },
  { key: "support.write", module: "support", description: "Create and update support tickets" },
  { key: "support.assign", module: "support", description: "Assign support tickets" },
  { key: "support.resolve", module: "support", description: "Resolve and reopen support tickets" },
  { key: "notifications.read", module: "notifications", description: "View notification campaigns" },
  { key: "notifications.write", module: "notifications", description: "Create and update notification campaigns" },
  { key: "notifications.send", module: "notifications", description: "Send notification campaigns" },
  { key: "notifications.schedule", module: "notifications", description: "Schedule notification campaigns" },
  { key: "notifications.cancel", module: "notifications", description: "Cancel notification campaigns" },
  { key: "roles.manage", module: "admin", description: "Manage admin roles and permissions" },
  { key: "admins.manage", module: "admin", description: "Manage admin users" },
];

export const ADMIN_ROLE_DEFINITIONS = [
  {
    key: "super-admin",
    name: "Super Admin",
    description: "Full internal access across the admin back office.",
    permissions: ADMIN_PERMISSION_DEFINITIONS.map((permission) => permission.key),
  },
  {
    key: "content-admin",
    name: "Content Admin",
    description: "Templates, spotlight, and moderation workflows.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "repits.read",
      "repits.moderate",
      "templates.read",
      "templates.write",
      "templates.publish",
      "templates.rollback",
      "templates.archive",
      "spotlight.read",
      "spotlight.write",
      "spotlight.publish",
      "spotlight.archive",
      "spotlight.schedule",
      "support.read",
    ],
  },
  {
    key: "support-admin",
    name: "Support Admin",
    description: "User support, diagnostics, and queue triage.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "users.read",
      "users.write",
      "users.suspend",
      "repits.read",
      "support.read",
      "support.write",
      "support.assign",
      "support.resolve",
      "notifications.read",
    ],
  },
  {
    key: "marketing-ops",
    name: "Marketing Ops",
    description: "Campaigns, growth operations, and spotlight reporting.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "spotlight.read",
      "spotlight.write",
      "spotlight.publish",
      "spotlight.archive",
      "spotlight.schedule",
      "notifications.read",
      "notifications.write",
      "notifications.send",
      "notifications.schedule",
      "notifications.cancel",
      "templates.read",
      "support.read",
    ],
  },
  {
    key: "read-only-analyst",
    name: "Read Only Analyst",
    description: "Read-only access to dashboards and audit history.",
    permissions: ["dashboard.read", "audit.read", "search.read"],
  },
] as const;

export const ADMIN_REQUIRED_PERMISSIONS_KEY = "admin:permissions";
