export type AdminPermissionDefinition = {
  key: string;
  module: string;
  description: string;
};

export const ADMIN_PERMISSION_DEFINITIONS: AdminPermissionDefinition[] = [
  { key: "dashboard.read", module: "dashboard", description: "View the admin dashboard" },
  { key: "audit.read", module: "audit", description: "View audit logs" },
  { key: "audit.export", module: "audit", description: "Export filtered audit records" },
  { key: "search.read", module: "search", description: "Use global admin search" },
  { key: "users.read", module: "users", description: "View users" },
  { key: "users.read_pii", module: "users", description: "View consumer personal information" },
  { key: "users.activity.read", module: "users", description: "View consumer activity" },
  { key: "users.diagnostics.read", module: "users", description: "View redacted consumer diagnostics" },
  { key: "users.export", module: "users", description: "Export filtered user records" },
  { key: "users.write", module: "users", description: "Update user profile data" },
  { key: "users.suspend", module: "users", description: "Suspend or reactivate users" },
  { key: "users.notes.create", module: "users", description: "Create internal consumer notes" },
  { key: "users.notes.read", module: "users", description: "View internal consumer notes" },
  { key: "users.restrictions.manage", module: "users", description: "Manage consumer restrictions" },
  { key: "users.recovery.manage", module: "users", description: "Initiate consumer recovery actions" },
  { key: "users.sessions.revoke", module: "users", description: "Revoke consumer sessions" },
  { key: "repits.read", module: "repits", description: "View repits" },
  { key: "repits.export", module: "repits", description: "Export filtered repit records" },
  { key: "repits.moderate", module: "repits", description: "Moderate repits" },
  { key: "repits.review", module: "repits", description: "Review moderation reports and evidence" },
  { key: "repits.assign", module: "repits", description: "Assign and claim moderation reports" },
  { key: "repits.decision", module: "repits", description: "Apply policy-backed moderation decisions" },
  { key: "repits.notes", module: "repits", description: "Create internal moderation notes" },
  { key: "repits.policy", module: "repits", description: "View moderation policy references" },
  { key: "repits.audit", module: "repits", description: "View repit moderation history" },
  { key: "repits.delete", module: "repits", description: "Delete repits" },
  { key: "templates.read", module: "templates", description: "View templates" },
  { key: "templates.write", module: "templates", description: "Create and edit templates" },
  { key: "templates.publish", module: "templates", description: "Publish template versions" },
  { key: "templates.rollback", module: "templates", description: "Rollback template versions" },
  { key: "templates.archive", module: "templates", description: "Archive templates" },
  { key: "spotlight.read", module: "spotlight", description: "View spotlight campaigns" },
  { key: "spotlight.write", module: "spotlight", description: "Create and edit spotlight campaigns" },
  { key: "spotlight.publish", module: "spotlight", description: "Publish spotlight campaigns" },
  { key: "spotlight.archive", module: "spotlight", description: "Archive spotlight campaigns" },
  { key: "spotlight.schedule", module: "spotlight", description: "Schedule spotlight campaigns" },
  { key: "support.read", module: "support", description: "View support tickets" },
  { key: "support.write", module: "support", description: "Create and update support tickets" },
  { key: "support.assign", module: "support", description: "Assign support tickets" },
  { key: "support.resolve", module: "support", description: "Resolve and reopen support tickets" },
  { key: "support.cases.read", module: "support", description: "View support cases" },
  { key: "support.cases.create", module: "support", description: "Create support cases" },
  { key: "support.cases.update", module: "support", description: "Classify and update support cases" },
  { key: "support.cases.assign", module: "support", description: "Claim, assign, reassign, and release support cases" },
  { key: "support.cases.respond", module: "support", description: "Send support responses" },
  { key: "support.cases.notes", module: "support", description: "Create internal support notes" },
  { key: "support.cases.escalate", module: "support", description: "Create and manage support escalations" },
  { key: "support.cases.resolve", module: "support", description: "Resolve support cases" },
  { key: "support.cases.reopen", module: "support", description: "Reopen resolved support cases" },
  { key: "support.cases.export", module: "support", description: "Export filtered support cases" },
  { key: "support.sla.read", module: "support", description: "View support SLA state" },
  { key: "support.sensitive_context.read", module: "support", description: "View permission-shaped linked support context" },
  { key: "notifications.read", module: "notifications", description: "View notification campaigns" },
  { key: "notifications.write", module: "notifications", description: "Create and update notification campaigns" },
  { key: "notifications.send", module: "notifications", description: "Send notification campaigns" },
  { key: "notifications.schedule", module: "notifications", description: "Schedule notification campaigns" },
  { key: "notifications.cancel", module: "notifications", description: "Cancel notification campaigns" },
  { key: "admins.read", module: "admin", description: "View the admin directory and access posture" },
  { key: "admins.invite", module: "admin", description: "Invite administrators" },
  { key: "admins.sessions.revoke", module: "admin", description: "Revoke administrator sessions" },
  { key: "admins.mfa.reset", module: "admin", description: "Require administrator MFA re-enrollment" },
  { key: "admins.mfa.disable", module: "admin", description: "Disable administrator MFA" },
  { key: "admins.access_review", module: "admin", description: "Complete administrator access reviews" },
  { key: "admins.break_glass", module: "admin", description: "Activate time-limited emergency access" },
  { key: "roles.manage", module: "admin", description: "Manage admin roles and permissions" },
  { key: "admins.manage", module: "admin", description: "Manage admin users" },
  { key: "platform.read", module: "platform", description: "View platform operations (config, flags, health)" },
  { key: "platform.write", module: "platform", description: "Manage platform config, feature flags, maintenance, and version control" },
  { key: "privacy.view", module: "privacy", description: "View privacy requests, jobs, and timelines" },
  { key: "privacy.assign", module: "privacy", description: "Assign and reassign privacy requests" },
  { key: "privacy.process", module: "privacy", description: "Advance, process, and retry privacy requests" },
  { key: "privacy.complete", module: "privacy", description: "Complete fulfilled privacy requests" },
  { key: "privacy.reject", module: "privacy", description: "Reject privacy requests" },
  { key: "privacy.export", module: "privacy", description: "Generate privacy data exports for secure subject delivery" },
  { key: "privacy.delete", module: "privacy", description: "Execute account-deletion fulfilment" },
  { key: "privacy.admin", module: "privacy", description: "Full privacy operations administration" },
  { key: "jobs.view", module: "jobs", description: "View platform jobs and status" },
  { key: "jobs.retry", module: "jobs", description: "Retry failed or dead-lettered jobs" },
  { key: "jobs.cancel", module: "jobs", description: "Cancel pending or scheduled jobs" },
  { key: "jobs.manage", module: "jobs", description: "Manage queues (pause/resume, configuration)" },
  { key: "jobs.view_payload", module: "jobs", description: "View job payload keys and metadata" },
  { key: "jobs.view_errors", module: "jobs", description: "View job error details and stacks" },
  { key: "media.read", module: "media", description: "View media processing queue and asset status" },
  { key: "media.manage", module: "media", description: "Retry and regenerate media processing" },
];

export const ADMIN_ROLE_DEFINITIONS = [
  {
    key: "super-admin",
    name: "Super Admin",
    description: "Full internal access across the admin back office.",
    permissions: ADMIN_PERMISSION_DEFINITIONS.map((permission) => permission.key),
  },
  {
    key: "content-admin",
    name: "Content Admin",
    description: "Templates, spotlight, and moderation workflows.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "repits.read",
      "repits.export",
      "repits.moderate",
      "repits.review",
      "repits.assign",
      "repits.decision",
      "repits.notes",
      "repits.policy",
      "repits.audit",
      "templates.read",
      "templates.write",
      "templates.publish",
      "templates.rollback",
      "templates.archive",
      "spotlight.read",
      "spotlight.write",
      "spotlight.publish",
      "spotlight.archive",
      "spotlight.schedule",
      "support.read",
      "support.cases.read",
      "support.cases.notes",
      "support.cases.escalate",
      "support.sla.read",
      "support.sensitive_context.read",
    ],
  },
  {
    key: "support-admin",
    name: "Support Admin",
    description: "User support, diagnostics, and queue triage.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "users.read",
      "users.read_pii",
      "users.activity.read",
      "users.diagnostics.read",
      "users.export",
      "users.write",
      "users.suspend",
      "users.notes.create",
      "users.notes.read",
      "users.restrictions.manage",
      "users.recovery.manage",
      "users.sessions.revoke",
      "repits.read",
      "repits.export",
      "repits.review",
      "repits.assign",
      "repits.notes",
      "repits.policy",
      "repits.audit",
      "support.read",
      "support.write",
      "support.assign",
      "support.resolve",
      "support.cases.read",
      "support.cases.create",
      "support.cases.update",
      "support.cases.assign",
      "support.cases.respond",
      "support.cases.notes",
      "support.cases.escalate",
      "support.cases.resolve",
      "support.cases.reopen",
      "support.cases.export",
      "support.sla.read",
      "support.sensitive_context.read",
      "notifications.read",
    ],
  },
  {
    key: "marketing-ops",
    name: "Marketing Ops",
    description: "Campaigns, growth operations, and spotlight reporting.",
    permissions: [
      "dashboard.read",
      "audit.read",
      "search.read",
      "spotlight.read",
      "spotlight.write",
      "spotlight.publish",
      "spotlight.archive",
      "spotlight.schedule",
      "notifications.read",
      "notifications.write",
      "notifications.send",
      "notifications.schedule",
      "notifications.cancel",
      "templates.read",
      "support.read",
      "support.cases.read",
    ],
  },
  {
    key: "read-only-analyst",
    name: "Read Only Analyst",
    description: "Read-only access to dashboards and audit history.",
    permissions: ["dashboard.read", "audit.read", "audit.export", "search.read"],
  },
] as const;

export const ADMIN_REQUIRED_PERMISSIONS_KEY = "admin:permissions";
